version: "3"

services:
  jaeger:
    image: jaegertracing/all-in-one:1.36.0
    ports:
      - "16686:16686"
      - "14250"

  zipkin:
    image: openzipkin/zipkin:2.23.0
    container_name: zipkin
    ports:
      - "9411:9411"

  otel-collector:
    image: otel/opentelemetry-collector:0.55.0
    ports:
      - "4317:4317"
    volumes:
      - ./otel-collector-config.yaml:/etc/otelcol/config.yaml:ro
    depends_on:
      - jaeger
      - zipkin
